### ISSUE TITLE
ROC-AUC-score calculation function error

### ISSUE THREAD

**Issue by Sowmya-R-Krishnan** [zfjsail/gae-pytorch#5]
In the code in utils.py, the function get_roc_score() has this line:

**labels_all = np.hstack([np.ones(len(preds)), np.zeros(len(preds))])**

The second argument should be **np.zeros(len(preds_neg))**

I was using your code to understand GVAE and found this small mistake. Thank you.

**Comment by zfjsail** [comment]
Thank you for pointing it out!
